version: "3.7"
services:
    web:
        container_name: web
        build: ./web-docker-image-conf
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web:/var/www/html
            - ./apache-conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./ssl-cert/priv_key.pem:/ssl-cert/priv_key.pem
            - ./ssl-cert/full_chain.pem:/ssl-cert/full_chain.pem
        networks:
            - web-network

networks:
  web-network:
